name: Create Release
run-name: ${{ github.actor }} generated new release
on: [push]
jobs:
  assignment3-expert-agent:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v1
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automatic release
          draft: false
          prerelease: false