name: GitHub Actions - Package Expert Agent Files
run-name: ${{ github.actor }} generated new agents files
on: [push]
jobs:
  assignment3-expert-agent:
    runs-on: ubuntu-latest
    steps:
      - run: cd /github/Assignment3/ExpertAgent/
      - name: Creating archive
        run: echo "hello"