name: GitHub Actions - Package Expert Agent Files
run-name: ${{ github.actor }} generated new agents files
on: [push]
jobs:
  assignment3-expert-agent:
    runs-on: ubuntu-latest
    steps:
      - run: cd /github/workspace/Assignment3/ExpertAgent/
      - name: Creating archive
        run: tar -cvf expert.tar -T EXPORT.TXT