name: GitHub Actions - Package Expert Agent Files
run-name: ${{ github.actor }} generated new agents files
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Creating archive
        run: echo "hello"